### ISSUE TITLE
redablestream

### ISSUE THREAD

**Issue by JamesTheFlash22** [kgurchiek/Minecraft-Server-Scanner-Discord-Bot#21]
![image](https://github.com/kgurchiek/Minecraft-Server-Scanner-Discord-Bot/assets/154464086/dd15b203-16a3-4991-9a9a-7c7cfa8fa464)

**Comment by kgurchiek** [comment]
What version of Node are you using?

**Comment by JamesTheFlash22** [comment]
Node 16

**Comment by JamesTheFlash22** [comment]
> What version of Node are you using?

Node 16

**Comment by JamesTheFlash22** [comment]
@kgurchiek

**Comment by kgurchiek** [comment]
try upgrading to 20

**Comment by JamesTheFlash22** [comment]
> try upgrading to 20

yes, now it goes, but doesn't register slash commands, i tried doing the deploy myself but it doesn't go, i'll wait for few hours if it takes a bit to register it

**Comment by JamesTheFlash22** [comment]
@kgurchiek 
![image](https://github.com/user-attachments/assets/05559942-7062-4532-b10e-638c41041ec9)

**Comment by JamesTheFlash22** [comment]
still loading after 3 hours

**Comment by kgurchiek** [comment]
sounds like it's having trouble connecting to the Discord API, where are you hosting it?

**Comment by JamesTheFlash22** [comment]
> sounds like it's having trouble connecting to the Discord API, where are you hosting it?

DanBotHosting, but was same w my PC It staid 10 mins

**Comment by kgurchiek** [comment]
That's weird. If you run `index.js` does it ever say that the bot logged in?

**Comment by JamesTheFlash22** [comment]
Yes It logs into the bot

Il sab 20 lug 2024, 02:24 Cornbread2100 ***@***.***> ha
scritto:

**Comment by JamesTheFlash22** [comment]
![Screenshot_2024-07-20-20-50-38-652_com android chrome](https://github.com/user-attachments/assets/4557ce6c-13d8-48b9-8c1f-6a089c78e49b)

**Comment by JamesTheFlash22** [comment]
Fixed idk how
